/**
 * V2: 스토리 캐릭터(name, appearance)를 Ref 탭 character 레퍼런스 카드로 upsert.
 *
 * 카드 prompt는 characterVisualPrompt(ethnicity, age, gender, appearance 조합) —
 * 캐릭터 이미지가 출신/인종·연령·성별을 반영한다. 시각 정보(ethnicity/appearance)가 둘 다
 * 없으면 빈 prompt(pending 카드).
 *
 * type-aware upsert(스펙 §3.1):
 *  - 같은 name + type==='character' 있으면 → 보존(사용자 생성/편집 이미지·status·prompt 불변).
 *  - 같은 name인데 type≠character(scene/style) → 추가 안 하고 collision 반환(태그만 있고 카드 없는
 *    조용한 실패 방지 — App이 토스트).
 *  - 없으면 → 전체 기본 필드 + numeric id로 추가(status:'pending', data:null).
 *
 * id는 numeric(앱이 ref.id를 숫자로 가정 — ReferencePanel Math.max, Number(id)). 문자열 id는 NaN을
 * 전파시키므로 금지. idempotency는 id가 아니라 name 보존으로 확보.
 */
// Ref 카드 이미지 프롬프트 조합 — 씬 프롬프트(electron buildPromptsPrompt/@멘션)와 동일 규칙을
// 공유 helper로 일원화.
import { characterVisualPrompt } from '../services/storyCharacter.js'

// 구 규칙(`${ethnicity}, ${appearance}` — age/gender 누락)이 만들었던 프롬프트. 기존 카드의
// prompt가 이 값과 정확히 같으면 "자동생성 후 손대지 않음"이므로 새 규칙으로 갱신해도 안전하다.
// 사용자가 직접 고쳐 쓴 프롬프트는 여기에 걸리지 않아 그대로 보존된다.
const trimmed = (v) => (typeof v === 'string' ? v.trim() : '')
function legacyVisualPrompt(c) {
  return [trimmed(c?.ethnicity), trimmed(c?.appearance)].filter(Boolean).join(', ')
}

export function upsertStoryCharacterRefs(existing, storyCharacters) {
  const refs = Array.isArray(existing) ? existing : []
  const chars = Array.isArray(storyCharacters) ? storyCharacters : []
  if (chars.length === 0) return { references: refs, collisions: [] }

  const byName = new Map(refs.map((r) => [r.name, r]))
  let nextId = refs.reduce((max, r) => (typeof r.id === 'number' && r.id > max ? r.id : max), 0)
  const added = []
  const collisions = []
  // 갱신본은 원본 ref 객체를 키로 들고 있는다. 이름으로 되꽂으면 같은 이름의 다른 ref
  // (스타일/씬 카드)까지 캐릭터 카드로 덮어써 조용히 사라진다.
  const patches = new Map()

  for (const c of chars) {
    const existingRef = byName.get(c.name)
    if (existingRef) {
      if (existingRef.type !== 'character') collisions.push(c.name) // 동명 비-character 충돌
      else {
        // §v2.12 FIX(MINOR): c.appearance가 아니라 조합 prompt 존재 여부로 보강 —
        // ethnicity-only 캐릭터도 pending 카드 prompt를 채운다(신규 카드 경로와 동일 규칙).
        // 비어 있는 prompt를 채우는 것에 더해, 구 규칙이 자동생성한 prompt(age/gender 누락)도
        // 갱신한다 — 그러지 않으면 기존 에피소드는 영영 성별·연령 없는 프롬프트로 남는다.
        const prompt = characterVisualPrompt(c)
        const autogenerated = !existingRef.prompt || existingRef.prompt === legacyVisualPrompt(c)
        if (autogenerated && prompt && prompt !== existingRef.prompt
          && existingRef.status === 'pending' && !existingRef.data && !existingRef.filePath && !existingRef.mediaId) {
          patches.set(existingRef, { ...existingRef, prompt })
        }
      }
      continue // character 동명은 보존(추가 안 함)
    }
    nextId += 1
    const card = {
      id: nextId,
      name: c.name,
      type: 'character',
      category: 'MEDIA_CATEGORY_SUBJECT',
      prompt: characterVisualPrompt(c),
      imagePath: '',
      data: null,
      mediaId: null,
      caption: '',
      status: 'pending',
      errorMessage: null,
    }
    byName.set(c.name, card)
    added.push(card)
  }

  const patchedRefs = patches.size ? refs.map((r) => patches.get(r) || r) : refs
  const references = added.length ? [...patchedRefs, ...added] : patchedRefs
  return { references, collisions }
}

export function assertStoryProjectCurrent(currentPath, enqueuedPath, message = 'stale story push discarded') {
  if (currentPath !== enqueuedPath) throw new Error(message)
}

export default { upsertStoryCharacterRefs, assertStoryProjectCurrent }
